version: '3'

services:
  local-spark:
    image: local-spark
    container_name: local-spark
    build:
      context: ./
      dockerfile: ./containers/spark/Dockerfile
    environment:
      METADATA_DRIVERNAME: postgresql
      METADATA_HOST: metadata
      METADATA_PORT: '5432'
      METADATA_USERNAME: sdeuser
      METADATA_PASSWORD: sdepassword
      METADATA_DATABASE: metadatadb
    volumes:
      - ./adventureworks:/opt/spark/work-dir/adventureworks
    ports:
      - "7077:7077" # Spark master submit port, if running
      - "4040:4040" # Spark application
      - "18080:18080" # History server

  minio:
    image: 'minio/minio:RELEASE.2023-07-21T21-12-44Z'
    hostname: minio
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server --console-address ":9001" /data

  metadata:
    image: postgres:15
    container_name: metadata
    environment:
      POSTGRES_USER: sdeuser
      POSTGRES_PASSWORD: sdepassword
      POSTGRES_DB: metadatadb
    ports:
      - "5432:5432"
    volumes:
      - ./containers/metadata/1-metadata-table.sql:/docker-entrypoint-initdb.d/init.sql

  createbuckets:
    image: minio/mc
    container_name: createbuckets
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c " /usr/bin/mc config host add myminio http://minio:9000 minio minio123; /usr/bin/mc rm -r --force myminio/adventureworks; /usr/bin/mc mb myminio/adventureworks; /usr/bin/mc policy download myminio/adventureworks; exit 0; "

  prometheus:
    image: prom/prometheus:v2.37.1
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  
  grafana:
    image: grafana/grafana:8.4.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=spark
    volumes:
      - ./monitoring/grafana/provisioning/:/etc/grafana/provisioning/